language: c

sudo: required

os:
  - linux
  - osx

matrix:
  allow_failures:
  - os: osx

env:
  global:
    - CHEZSCHEMELIBDIRS="${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}/thunderchez"
    - DEPLOY_FILE="chez-string_metrics_`uname`_`uname -m`"
    - CC=gcc    
    - SCHEME=$HOME/ChezScheme/bin/scheme    
  
addons:
  homebrew:
    update: true
    packages:
      - aria2
      - ncurses
      - ossp-uuid
  apt:
    update: true
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev
      - uuid-dev
      - zlib1g-dev
      - aria2

before_install:  
  - /bin/bash -e ./.travis/install_chez
  - pushd ${TRAVIS_BUILD_DIR}
  - CHEZ_MACHINETYPE=$(echo "(machine-type)" | $SCHEME -q)
  - echo ${CHEZ_MACHINETYPE}
  - CHEZ_KERNEL="$HOME/ChezScheme/lib/csv9.5.2/${CHEZ_MACHINETYPE}" $SCHEME --script "build.ss"
  - popd

script:
  - $SCHEME --script "${TRAVIS_BUILD_DIR}/tests.ss"

before_deploy:
  - rm -rf chez-string-metrics/*
  - mv string-matrics.so chez-string-metrics
  - mv libstring_metrics.* chez-string-metrics
  - zip -r $DEPLOY_FILE.zip chez-string-metrics
  - tar czf $DEPLOY_FILE.tar.gz chez-string-metrics

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - $DEPLOY_FILE.zip
    - $DEPLOY_FILE.tar.gz
  skip_cleanup: true
  on:
    tags: true
  # draft: true
  overwrite: true
